'use strict';

module.exports = [

    // specify the deafult tags for all the routes here.
    // this will be used if the tags for given url is not specified here.
    {
        url: 'about',
        title: 'PT. HBU Express - Kirim Paket Murah, Jemput Paket, Jasa Pengiriman Dokumen, Kirim Paket Tangerang.',
        description: 'Kirim Paket Murah, Jemput Paket, Jasa Pengiriman Dokumen, Kirim Paket Tangerang, Jasa Kirim Paket Terdekat, Jasa Expedisi Cargo',
        keywords: 'ekspedisi jemput paket Tangerang, gratis jemput kiriman paket Tangerang, jasa expedisi cargo Tangerang, jasa expedisi cargo 2020 Jakarta, jasa expedisi cargo 2021 Tangerang, jasa expedisi cargo 2022 Tangerang, jasa jemput paket Tangerang, jasa kirim dokumen cepat Jakarta , jasa kirim dokumen ke luar negeri Tangerang, jasa kirim paket Tangerang, jasa kirim paket 1 hari sampai Tangerang, jasa kirim paket ke luar negeri Jakarta, jasa kirim paket ke luar negeri murah Tangerang, jasa kirim paket ke luar negeri terdekat Tangerang, jasa kirim paket ke malaysia Tangerang, jasa kirim paket luar negeri terdekat Jakarta, jasa kirim paket murah Tangerang, jasa kirim paket terdekat Tangerang, jasa kirim paket terdekat Tangerang, jasa kirim paket terdekat 2020 Jakarta, jasa kirim paket terdekat 2021 Tangerang, jasa kirim paket terdekat 2022 Tangerang, jasa kirim paket terdekat 24 jam Tangerang, jasa kirim paket terdekat amerika Jakarta, jasa kirim paket terdekat barang Tangerang, jasa kirim paket terdekat express Tangerang, jasa kirim paket terdekat qatar Tangerang, jasa kirim paket yang murah Jakarta, jasa kurir jemput paket di rumah Tangerang, jasa kurir kirim paket barang 1 hari sampai Tangerang, jasa pengiriman barang atau dokumen Tangerang, jasa pengiriman barang terdekat dari lokasi saya Jakarta, jasa pengiriman dokumen Tangerang, jasa pengiriman dokumen barang Tangerang, jasa pengiriman dokumen barang document Tangerang, jasa pengiriman dokumen ekspor Jakarta, jasa pengiriman dokumen global Tangerang, jasa pengiriman dokumen indonesia Tangerang, jasa pengiriman dokumen inggris Tangerang, jasa pengiriman dokumen internasional Jakarta, jasa pengiriman dokumen ke china Tangerang, jasa pengiriman dokumen ke luar negeri Tangerang, jasa pengiriman dokumen luar negeri Tangerang, jasa pengiriman dokumen murah Jakarta, jasa pengiriman dokumen paling aman Tangerang, jasa pengiriman dokumen paling cepat Tangerang, jasa pengiriman dokumen penting Tangerang, jasa pengiriman dokumen resmi Jakarta, jasa pengiriman dokumen resmi jakarta Tangerang, jasa pengiriman dokumen tercepat Tangerang, jasa pengiriman dokumen terdekat Tangerang, jasa pengiriman dokumen yang aman Jakarta, jasa pengiriman indonesia ke amerika Tangerang, jasa pengiriman paket dokumen Tangerang, jemput paket Tangerang, jemput paket di rumah Jakarta, jemput paket hari ini Tangerang,',
    },

    {
        url: 'services',
        title: 'PT. HBU Express - Kirim Paket Murah, Jemput Paket, Jasa Pengiriman Dokumen, Kirim Paket Tangerang.',
        description: 'Kirim Paket Murah, Jemput Paket, Jasa Pengiriman Dokumen, Kirim Paket Tangerang, Jasa Kirim Paket Terdekat, Jasa Expedisi Cargo',
        keywords: 'jemput paket ke rumah Tangerang, kirim barang 1 ton Tangerang, kirim barang 100 kg Jakarta, kirim barang 30 kg Tangerang, kirim barang 50 kg Tangerang, kirim barang besar murah Tangerang, kirim barang murah cargo Jakarta, kirim barang murah indonesia Tangerang, kirim barang murah ke singapore Tangerang, kirim barang ongkir murah Tangerang, kirim barang paling murah ke luar negeri Jakarta, kirim barang ukuran besar Tangerang, kirim barang yang murah Tangerang, kirim paket Tangerang, kirim paket 10 kg Jakarta, kirim paket 100kg Tangerang, kirim paket 10kg murah Tangerang, kirim paket 20 kg murah Tangerang, kirim paket 20kg murah Jakarta, kirim paket 24 jam Tangerang, kirim paket 30kg Tangerang, kirim paket barang yang murah Tangerang, kirim paket barang yang murah Jakarta, kirim paket bayar di tempat tujuan Tangerang, kirim paket bayar penerima Tangerang, kirim paket berat 5 kg Tangerang, kirim paket berat yang murah Jakarta, kirim paket berat yang murah Tangerang, kirim paket besar Tangerang, kirim paket besar murah Tangerang, kirim paket besar murah Jakarta, kirim paket cargo Tangerang, kirim paket cargo murah Tangerang, kirim paket cepat Tangerang, kirim paket cepat dan murah Jakarta, kirim paket dari rumah Tangerang, kirim paket dijemput Tangerang, kirim paket dokumen Tangerang, kirim paket ekspedisi Jakarta, kirim paket express Tangerang, kirim paket gratis Tangerang, kirim paket hari ini sampai Tangerang, kirim paket hari minggu Jakarta, kirim paket hari yang sama Tangerang, kirim paket indonesia ke australia Tangerang, kirim paket indonesia ke jepang Tangerang, kirim paket indonesia ke malaysia Jakarta, kirim paket instan Tangerang, kirim paket instan murah Tangerang, kirim paket instant Tangerang, kirim paket internasional Jakarta, kirim paket internasional murah Tangerang, kirim paket ke amerika Tangerang, kirim paket ke amerika murah Tangerang, kirim paket ke amerika paling murah Jakarta, kirim paket ke amerika paling murah Tangerang, kirim paket ke arab saudi murah Tangerang,',
    },

    {
        url: 'gallery',
        title: 'PT. HBU Express - Kirim Paket Murah, Jemput Paket, Jasa Pengiriman Dokumen, Kirim Paket Tangerang.',
        description: 'kirim paket ke australia Tangerang, kirim paket ke australia murah Jakarta, kirim paket ke australia paling murah Tangerang, kirim paket ke belanda murah Tangerang, kirim paket ke china murah Tangerang, kirim paket ke dubai murah Jakarta, kirim paket ke hongkong murah Tangerang, kirim paket ke hongkong paling murah Tangerang, kirim paket ke india murah Tangerang, kirim paket ke jepang murah Jakarta, kirim paket ke jepang paling murah Tangerang, kirim paket ke jerman murah Tangerang, kirim paket ke luar negeri Tangerang, kirim paket ke luar negeri hbu Jakarta, kirim paket ke luar negeri murah Tangerang, kirim paket ke luar negeri paling murah Tangerang, kirim paket ke luar negeri yang murah Tangerang, kirim paket ke malaysia Jakarta, kirim paket ke malaysia murah Tangerang, kirim paket ke malaysia murah 2020 Tangerang, kirim paket ke malaysia murah 2021 Tangerang, kirim paket ke malaysia murah 2022 Jakarta, kirim paket ke malaysia yang murah Tangerang, kirim paket ke qatar Tangerang, kirim paket ke rusia Tangerang, kirim paket ke singapore Jakarta, kirim paket ke singapore murah Tangerang, kirim paket ke singapura murah Tangerang, kirim paket ke singapura via wahana Tangerang, kirim paket ke sydney murah Jakarta, kirim paket ke taiwan murah Tangerang, kirim paket ke taiwan paling murah Tangerang, kirim paket ke turki murah Tangerang, kirim paket ke uk Jakarta, kirim paket ke usa Tangerang, kirim paket keluar negeri murah Tangerang, kirim paket keluar negeri termurah Tangerang, kirim paket luar negeri Jakarta, kirim paket luar negeri murah Tangerang, kirim paket makanan ke luar negeri Tangerang, kirim paket malaysia murah Tangerang, kirim paket murah Jakarta, kirim paket murah jakarta Tangerang, kirim paket murah ke amerika Tangerang, kirim paket murah ke australia Tangerang, kirim paket murah ke eropa Jakarta, kirim paket murah ke hongkong Tangerang, kirim paket murah ke inggris Tangerang, kirim paket murah ke luar negeri Tangerang, kirim paket murah ke malaysia Jakarta, kirim paket murah ke thailand Tangerang, kirim paket murah luar negeri Tangerang, kirim paket murah qatar Tangerang, kirim paket murah qatar 2022 Jakarta, kirim paket murah terdekat Tangerang, kirim paket murah xpress Tangerang, kirim paket next day Tangerang,',
    },

    {
        url: 'contact',
        title: 'PT. HBU Express - Kirim Paket Murah, Jemput Paket, Jasa Pengiriman Dokumen, Kirim Paket Tangerang.',
        description: 'kirim paket one day service Jakarta, kirim paket ongkir ditanggung penerima Tangerang, kirim paket ongkir murah Tangerang, kirim paket paling murah Tangerang, kirim paket paling murah Jakarta, kirim paket paling murah lewat apa Tangerang, kirim paket pick up Tangerang, kirim paket pick up ke rumah Tangerang, kirim paket reguler Jakarta, kirim paket tangerang Tangerang, kirim paket tangerang 2020 Tangerang, kirim paket tangerang 2021 Tangerang, kirim paket tangerang 2022 Jakarta, kirim paket tangerang indonesia Tangerang, kirim paket tanpa keluar rumah Tangerang, kirim paket tercepat Tangerang, kirim paket terdekat Jakarta, kirim paket termurah Tangerang, kirim paket termurah 2020 Tangerang, kirim paket termurah 2021 Tangerang, kirim paket termurah 2021 Jakarta, kirim paket termurah 2022 Tangerang, kirim paket volume murah Tangerang, kirim paket yang bayar penerima Tangerang, kirim paket yang bisa cod Jakarta, kirim paket yang bisa jemput ke rumah Tangerang, kirim paket yang cepat Tangerang, kirim paket yang murah Tangerang, kirim paket yang murah Jakarta, kurir jemput paket Tangerang, kurir yang bisa jemput paket Tangerang, layanan antar jemput paket Tangerang, layanan jemput paket Jakarta, layanan jemput paket ke rumah Tangerang, layanan kirim paket jemput ke rumah Tangerang, layanan kirim paket ke luar negeri Tangerang, melayani antar jemput paket Jakarta, paket bisa di jemput Tangerang, paket di jemput Tangerang, paket express 1 hari sampai Tangerang, paket kirim barang paling murah Jakarta, paket yang bisa jemput ke rumah Tangerang, pengiriman 1 hari sampai Tangerang, pengiriman barang cargo murah Tangerang, pengiriman barang yang murah Jakarta, pengiriman paket 24 jam Tangerang, pengiriman paket 24 jam terdekat Tangerang, pengiriman paket antar jemput Tangerang, pengiriman paket jemput Jakarta, pengiriman paket murah dan cepat Tangerang, pengiriman paket murah ke jepang Tangerang, pengiriman paket termurah dan cepat Tangerang, pengiriman paket termurah di indonesia Jakarta, pengiriman paket yang buka hari minggu Tangerang, promo kirim paket Tangerang, rekomendasi kirim paket ke luar negeri Tangerang,tempat kirim paket terdekat Jakarta,',
    },
];